kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: issuesnap
  labels:
    app: issuesnap
  namespace: your-namespace # Change to your namespace
  annotations:
    kubernetes.io/tls-acme: 'true'
spec:
  rules:
    - host: issuesnap.oursky.com # Change to your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: issuesnap
                port:
                  number: 80
  tls:
    - hosts:
        - issuesnap.oursky.com # Change to your domain
      secretName: issuesnap-tls
