apiVersion: v1
kind: Service
metadata:
  labels:
    app: issuesnap
  name: issuesnap
  namespace: your-namespace # Change to your namespace
spec:
  selector:
    app.kubernetes.io/component: issuesnap
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
